# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-16 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_temp', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('summit_temp', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('resort', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resorts.Resort')),
            ],
            options={
                'verbose_name_plural': 'Conditions',
            },
        ),
        migrations.AlterModelOptions(
            name='skipass',
            options={'verbose_name_plural': 'Ski passes'},
        ),
    ]
