# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-08 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0006_auto_20171008_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditions',
            name='resort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resorts.Resort'),
        ),
    ]
