# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-08 20:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0008_conditions_checker_runtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conditions',
            name='resort',
        ),
    ]
