# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-08 20:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0011_auto_20171008_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conditions',
            old_name='url',
            new_name='conditions_page_url',
        ),
    ]
