# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-08 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0013_remove_resort_conditions_page_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='resort',
            name='conditions_page_url',
            field=models.URLField(blank=True),
        ),
    ]
