# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resort_name', models.CharField(max_length=200)),
                ('resort_address', models.CharField(max_length=200)),
                ('lift_ticket_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rental_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
