# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorthub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resort',
            name='season_begins',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='resort',
            name='resort_address',
            field=models.CharField(max_length=400),
        ),
    ]
