# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorthub', '0002_auto_20170528_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='resort',
            name='max_pass',
            field=models.BooleanField(default=True),
        ),
    ]
