# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 21:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resorthub', '0003_resort_max_pass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resort',
            old_name='max_pass',
            new_name='maxx_pass',
        ),
    ]
