# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('resorthub', '0005_auto_20170528_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resort',
            name='resort_address',
        ),
        migrations.AddField(
            model_name='resort',
            name='resort_city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='resort',
            name='resort_state',
            field=localflavor.us.models.USStateField(default='VT', max_length=2),
        ),
        migrations.AddField(
            model_name='resort',
            name='resort_street_address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='resort',
            name='resort_zip',
            field=localflavor.us.models.USZipCodeField(default='05149', max_length=10),
        ),
    ]
