# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('resorthub', '0006_auto_20170529_0748'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternationalResort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resort_province', models.CharField(default='', max_length=50)),
                ('resort_zip', models.CharField(default='H1A0A1', max_length=10)),
                ('resort_country', django_countries.fields.CountryField(default='CAN', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='USResort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resort_state', localflavor.us.models.USStateField(default='VT', max_length=2)),
                ('resort_zip', localflavor.us.models.USZipCodeField(default='05149', max_length=10)),
                ('resort_country', django_countries.fields.CountryField(default='USA', max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='Resort',
        ),
    ]
