# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resorthub', '0007_auto_20170529_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='internationalresort',
            name='available_passes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('NON', 'None'), ('EPI', 'Epic Pass'), ('MAX', 'Max Pass'), ('MOC', 'Mountain Collective Pass'), ('NEP', 'New England Pass'), ('PEA', 'Peak Pass'), ('POW', 'Powder Alliance Pass'), ('ROC', 'Rocky Mountain Super Pass')], default='NON', max_length=31),
        ),
        migrations.AddField(
            model_name='internationalresort',
            name='eight_day_snowfall',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='internationalresort',
            name='five_day_snowfall',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='internationalresort',
            name='four_day_snowfall',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='internationalresort',
            name='lift_ticket_price',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='internationalresort',
            name='nine_day_snowfall',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='internationalresort',
            name='one_day_snowfall',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='internationalresort',
            name='rental_price',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='internationalresort',
            name='resort_city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='internationalresort',
            name='resort_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='internationalresort',
            name='resort_street_address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='internationalresort',
            name='season_begins',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='internationalresort',
            name='seven_day_snowfall',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='internationalresort',
            name='six_day_snowfall',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='internationalresort',
            name='ten_day_snowfall',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='internationalresort',
            name='three_day_snowfall',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='internationalresort',
            name='two_day_snowfall',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usresort',
            name='available_passes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('NON', 'None'), ('EPI', 'Epic Pass'), ('MAX', 'Max Pass'), ('MOC', 'Mountain Collective Pass'), ('NEP', 'New England Pass'), ('PEA', 'Peak Pass'), ('POW', 'Powder Alliance Pass'), ('ROC', 'Rocky Mountain Super Pass')], default='NON', max_length=31),
        ),
        migrations.AddField(
            model_name='usresort',
            name='eight_day_snowfall',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usresort',
            name='five_day_snowfall',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usresort',
            name='four_day_snowfall',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usresort',
            name='lift_ticket_price',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='usresort',
            name='nine_day_snowfall',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usresort',
            name='one_day_snowfall',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usresort',
            name='rental_price',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='usresort',
            name='resort_city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='usresort',
            name='resort_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='usresort',
            name='resort_street_address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='usresort',
            name='season_begins',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usresort',
            name='seven_day_snowfall',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usresort',
            name='six_day_snowfall',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usresort',
            name='ten_day_snowfall',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usresort',
            name='three_day_snowfall',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usresort',
            name='two_day_snowfall',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='internationalresort',
            name='resort_country',
            field=django_countries.fields.CountryField(default='CA', max_length=2),
        ),
        migrations.AlterField(
            model_name='usresort',
            name='resort_country',
            field=django_countries.fields.CountryField(default='US', max_length=2),
        ),
    ]
