# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 13:13
from __future__ import unicode_literals

import address.models
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('resorthub', '0008_auto_20170529_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resort_name', models.CharField(default='', max_length=200)),
                ('lift_ticket_price', models.DecimalField(decimal_places=2, default=100.0, max_digits=6)),
                ('rental_price', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('season_begins', models.DateField(auto_now=True)),
                ('available_passes', multiselectfield.db.fields.MultiSelectField(choices=[('NON', 'None'), ('EPI', 'Epic Pass'), ('MAX', 'Max Pass'), ('MOC', 'Mountain Collective Pass'), ('NEP', 'New England Pass'), ('PEA', 'Peak Pass'), ('POW', 'Powder Alliance Pass'), ('ROC', 'Rocky Mountain Super Pass')], default='NON', max_length=31)),
                ('one_day_snowfall', models.IntegerField(default=0)),
                ('two_day_snowfall', models.IntegerField(default=0)),
                ('three_day_snowfall', models.IntegerField(default=0)),
                ('four_day_snowfall', models.IntegerField(default=0)),
                ('five_day_snowfall', models.IntegerField(default=0)),
                ('six_day_snowfall', models.IntegerField(default=0)),
                ('seven_day_snowfall', models.IntegerField(default=0)),
                ('eight_day_snowfall', models.IntegerField(default=0)),
                ('nine_day_snowfall', models.IntegerField(default=0)),
                ('ten_day_snowfall', models.IntegerField(default=0)),
                ('resort_address', address.models.AddressField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='address.Address')),
            ],
        ),
        migrations.DeleteModel(
            name='InternationalResort',
        ),
        migrations.DeleteModel(
            name='USResort',
        ),
    ]
