# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorthub', '0009_auto_20170529_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='resort',
            name='maxx_pass',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='resort',
            name='eight_day_snowfall',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='resort',
            name='five_day_snowfall',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='resort',
            name='four_day_snowfall',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='resort',
            name='nine_day_snowfall',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='resort',
            name='one_day_snowfall',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='resort',
            name='seven_day_snowfall',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='resort',
            name='six_day_snowfall',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='resort',
            name='ten_day_snowfall',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='resort',
            name='three_day_snowfall',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='resort',
            name='two_day_snowfall',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
