# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resorthub', '0010_auto_20170529_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resort',
            name='maxx_pass',
        ),
    ]
