# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 13:53
from __future__ import unicode_literals

import address.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resorthub', '0012_auto_20170529_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_runs', multiselectfield.db.fields.MultiSelectField(choices=[('BE', 'Beginner'), ('IN', 'Intermediate'), ('EX', 'Expert'), ('TE', 'Freestyle'), ('GL', 'Glades')], default='BE', max_length=14)),
                ('pass_type', models.CharField(choices=[('NON', 'None'), ('EPI', 'Epic Pass'), ('MAX', 'Max Pass'), ('MOC', 'Mountain Collective Pass'), ('NEP', 'New England Pass'), ('PEA', 'Peak Pass'), ('POW', 'Powder Alliance Pass'), ('ROC', 'Rocky Mountain Super Pass')], default='NON', max_length=20)),
                ('own_equipment', models.BooleanField(default=False)),
                ('address', address.models.AddressField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='address.Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
