# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorthub', '0015_auto_20170604_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='resort',
            name='num_black',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resort',
            name='num_blue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resort',
            name='num_doubb',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resort',
            name='num_green',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resort',
            name='num_open',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resort',
            name='num_slopes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resort',
            name='snow_site',
            field=models.CharField(default='', max_length=100),
        ),
    ]
