# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_scraper', '0025_new_follow_pages_page_xpath_pagination_attribute'),
        ('resorthub', '0016_auto_20170704_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrailPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(default='')),
                ('num_open', models.IntegerField(default=0)),
                ('base_temp', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('summit_temp', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('new_snow', models.DecimalField(decimal_places=4, default=0, max_digits=4)),
                ('checker_runtime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dynamic_scraper.SchedulerRuntime')),
            ],
        ),
        migrations.RemoveField(
            model_name='resort',
            name='num_doubb',
        ),
        migrations.RemoveField(
            model_name='resort',
            name='snow_site',
        ),
        migrations.AddField(
            model_name='resort',
            name='scraper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dynamic_scraper.Scraper'),
        ),
        migrations.AddField(
            model_name='resort',
            name='scraper_runtime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dynamic_scraper.SchedulerRuntime'),
        ),
        migrations.AddField(
            model_name='resort',
            name='url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='resort',
            name='web_home',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='trailpage',
            name='resort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resorthub.Resort'),
        ),
    ]
