# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-07 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resorthub', '0017_auto_20170705_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resort',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='trailpage',
            name='resort',
            field=models.ForeignKey(default=4, null=True, on_delete=django.db.models.deletion.CASCADE, to='resorthub.Resort'),
        ),
        migrations.AlterField(
            model_name='trailpage',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
