# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-07 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorthub', '0018_auto_20170707_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resort',
            name='num_open',
        ),
        migrations.AlterField(
            model_name='trailpage',
            name='num_open',
            field=models.IntegerField(default=999),
        ),
    ]
