# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-07 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorthub', '0019_auto_20170707_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailpage',
            name='new_snow',
            field=models.CharField(default='', max_length=100),
        ),
    ]
