# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-07 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorthub', '0020_auto_20170707_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='resort',
            name='num_doubb',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_resorts',
            field=models.ManyToManyField(blank=True, null=True, to='resorthub.Resort'),
        ),
    ]
