# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-08 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorthub', '0022_resort_our_take'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailpage',
            name='summit_temp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
