# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-08 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorthub', '0023_auto_20170908_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailpage',
            name='base_temp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
