# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-16 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resorthub', '0002_auto_20170912_0913'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resort',
            new_name='OldResort',
        ),
    ]
