# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-16 16:25
from __future__ import unicode_literals

import address.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('website', models.URLField(default='')),
                ('adult_lift_ticket', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('combo_rental', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('opening_date', models.DateField(auto_now=True)),
                ('num_slopes', models.IntegerField(default=0)),
                ('num_beginner', models.IntegerField(default=0)),
                ('num_intermediate', models.IntegerField(default=0)),
                ('num_advanced', models.IntegerField(default=0)),
                ('num_expert', models.IntegerField(default=0)),
                ('num_terrain', models.IntegerField(default=0)),
                ('our_take', models.CharField(default='This resort is great! Yay, skiing!', max_length=1000)),
                ('address', address.models.AddressField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='address.Address')),
            ],
        ),
        migrations.CreateModel(
            name='SkiPass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('resorts', models.ManyToManyField(to='resorts.Resort')),
            ],
        ),
    ]
