# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-08 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0009_remove_conditions_resort'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditions',
            name='resort',
            field=models.ForeignKey(default=6, null=True, on_delete=django.db.models.deletion.CASCADE, to='resorts.Resort'),
        ),
    ]
