# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-08 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0012_auto_20171008_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resort',
            name='conditions_page_url',
        ),
    ]
