# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-09 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0014_resort_conditions_page_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditions',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
