# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-09 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0015_conditions_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conditions',
            old_name='name',
            new_name='unique_id',
        ),
    ]
